FROM ros:noetic

RUN apt update && apt install -q -y --no-install-recommends \
    git \
    python3-catkin-tools

RUN apt update && apt install -q -y --no-install-recommends \
    ros-noetic-eigen-conversions \
    libgoogle-glog-dev

WORKDIR /root/ros_ws
