name: Python API

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - name: Fetch the package's repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Build
        run: python -m pip install -v ./library/python/

  test:
    name: Test
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - name: Fetch the package's repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Test
        run: |
          python -m pip install -v './library/python[test]'
          pytest -rAv ./library/python/
